name: PR Target Workflow

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions: {}

jobs:
  pr-target-check:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@v4

      - name: Wait for 2 minutes
        run: sleep 120
