name: Unexpected Outbound Calls
on:
  workflow_dispatch:
permissions: {}

jobs:
  unexpected-outbound-calls:
    permissions:
      contents: read
    name: UnexpectedOutboundCalls
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit
      - run: "curl https://attacker.com -L  || true"
      - run: "curl https://google.com -L  || true"
      - run: "curl microsoft.com:443  --connect-timeout 5 || true"
      - run: "curl amazon.com:443  --connect-timeout 5 || true"
